sudo: required
cache: yarn
language: node_js
node_js:
  - "6"
services:
  - docker
env:
  global:
    - CF_CLI_VERSION=6.25.0
before_install:
  - docker-compose --version
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get -qq update && sudo apt-get -qq install yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - dpkg -L <packagename>
  - yarn --version
install:
  - yarn --pure-lockfile
  - npm run build-docker
  - docker-compose build
script:
  - npm run eslint .
  - npm test
  - npm run test-docker
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=$CF_CLI_VERSION"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
deploy:
  - provider: script
    script: ./deploy-travis.sh
    skip_cleanup: true
    on:
      branch: master
