version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install yarn
          command: sudo npm install -g yarn
      - run:
          name: Display versions
          command: |
            echo $(node --version)
            echo $(yarn --version)
            echo $(npm --version)
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
      - run:
          name: Run dependencies
          command: docker-compose --version
          command: yarn --version
          command: yarn --pure-lockfile
          command: yarn build-docker
          command: docker-compose build
      - run:
          name: Run tests
          command: yarn eslint .
          command: yarn test
          command: yarn test-docker

      - deploy:
          name: Deploy to production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy-circle.sh
            fi
